### PR TITLE
remove dead Python2 code

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by muelli** [comment]
Wow, excellent! Thanks!
Have you tested basic functionality by any chance? It looks very innocent, though...

**Comment by a-detiste** [comment]
Of course I did not tested 😁

But already I submitted tens of similar PR and always test the result with mypy


https://wiki.debian.org/Python3-six-removal

**Comment by a-detiste** [comment]
I did à review of my proposed changes.
This line is dumb but it will work still.

```
-from io import StringIO as StringIO
+from io import StringIO
```

**Comment by a-detiste** [comment]
"Debian and Ubuntu dependencies" in the homepage needs to be adapred too.

We are removing python3-future anytime soon.

**Comment by a-detiste** [comment]
Ping

**Comment by a-detiste** [comment]
https://tracker.debian.org/news/1496855/gnome-keysign-removed-from-testing/

**Pull request merged**
