### PR TITLE
Allocate Bluetooth code with inlineCallbacks

### PR DESCRIPTION
**Pull request by RyuzakiKK**
This fix is related to the PR #52
Now we defer `get_local_bt_address` to a different thread. In this way
we don't stall the UI waiting for this method reply.

### CODE REVIEW

**Comment by muelli** [comment]
cool.

do all the callers need to be changed? e.g. https://github.com/gnome-keysign/gnome-keysign/blob/d40ee783ec0c7589c604bc332f6c3b05cf15b37f/keysign/bluetoothoffer.py#L137

otherwise LGTM

**Comment by RyuzakiKK** [comment]
That case is already covered here https://github.com/gnome-keysign/gnome-keysign/pull/63/files#diff-09986ff757be14a66c64dde5330d20f8R155

**Comment by muelli** [comment]
ah. k. I'm being stupid. The code I linked to will be changed. 
But the answer seems to be "yes, all callers of that function need to be adapted".
And all the callers have been changed in this PR, correct?

**Comment by RyuzakiKK** [comment]
Exactly.

**Pull request merged**
