### PR TITLE
"here" to "No GNOME Keysign servers around"

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by muelli** [comment]
This is how it looks with your proposed modification:

image


It's indeed odd to have the same sentence twice.

**Comment by muelli** [comment]
What do you think about replacing "here" with "the documentation"?
Unless you have another suggestion I'd rather close this proposal.

**Comment by scootergrisen** [comment]
Sure use "the documentation".
Its better then "here".
I see "here" links on website and they are not so good because then you end up with alot of "click here", "and here" and "here" links that does tell the user much.

**Comment by muelli** [comment]
with 99679c7 we have 

image

**Pull request closed without merging**
