### PR TITLE
Updated requirements.txt to add twisted

### PR DESCRIPTION
**Pull request by PadamSethia**
On running python -m app.py , it shows `module twisted.internet not found` .
Hence the addition of twisted package name to the requirements.txt

### CODE REVIEW

**Comment by RyuzakiKK** [comment]
Thanks for the patch.
You should move `twisted` up, under the `# Python packages` group.

**Comment by PadamSethia** [comment]
Done !

**Comment by muelli** [comment]
cool. thanks. can you squash your three commits into one?

**Comment by muelli** [comment]
ah. actually, we're not using `requirements.txt` anymore.

**Pull request closed without merging**
